DROP TABLE IF EXISTS conte;
DROP TABLE IF EXISTS recepta;
DROP TABLE IF EXISTS ingredient;
DROP TABLE IF EXISTS familiaIngredient;
DROP TABLE IF EXISTS tipusDeMenjar;
DROP TABLE IF EXISTS plat;
DROP TABLE IF EXISTS chef;